### PR TITLE
Switch IDPair to SIMD

### PR DESCRIPTION
**Pull request by Benny-Nottonson**
This pull request switches the `IDPair` struct to use SIMD (Single Instruction, Multiple Data) for improved performance. The `IDPair` struct now uses a SIMD array of `uint64` to store the `id1` and `id2` values. Additionally, small changes have been made to improve code readability and maintainability.

### CODE REVIEW

**Comment by Benny-Nottonson** [comment]
Let me know how that affects performance on your machine, just trying to push it past the Rust implementation

**Comment by dorjeduck** [comment]
Hi Benny, thanks for this. Do you notice significant performance gains by this change? I am asking as I see right now only very small performance gains, and wondering does changing to SIMD type brings benefits in itself even so no SIMD operations are taking place?  Switching from .id1 and id2 to data[0] and data[1] reduces code readability so i just want to get sorted what we gain for that. Happy to accept the pull request but need to understand ...

**Comment by dorjeduck** [comment]
anyway, i think the suggestion actually makes sense, thanks again

**Comment by Benny-Nottonson** [comment]
I did get slight gains on my machine, there are SIMD operations going on in the __eq__ and __ne__ methods (although they are hidden by an implicit cast). That being said, you could use WAY more SIMD

**Pull request merged**
